### ISSUE TITLE
Add AoE 4 World Units Page

### ISSUE THREAD

**Issue by aquaductape** [thetarnav/made-in-solid#4]
Proof: https://discord.com/channels/722131463138705510/734440921776783391/959557903843467344

Url: https://aoe4world.com/explorer/units

You could put this url instead https://aoe4world.com/explorer/, since it also uses solid-js, by checking devtools that it uses `Symbol("solid-proxy")`

**Comment by thetarnav** [comment]
Ah yes, forgot about this one.
Why the units page specifically when the whole `/explore` is using solid?

**Comment by aquaductape** [comment]
> Why the units page specifically when the whole /explore is using solid?

The poster shared `/explorer/units`, then I discovered that `/explorer` uses solid. I think the poster decided to share that url because it featured more cool state changes/animations when shifting through the "ages" buttons. 

<img width="152" alt="Screenshot 2023-03-28 at 1 02 40 AM" src="https://user-images.githubusercontent.com/29286430/228169782-9ff2c584-2ac0-440b-9f8b-51f6a0581b41.png">

I don't care which url we choose, but wanted to give you more information.

Edit: Ah you found the repo, lazy me didn't search "aoe4 github", yeah choosing `/explorer` is better since it fits will with repo url https://github.com/aoe4world/explorer
